development: &defaults
  adapter:  mysql
  database: billtrack_member
  username: root
  password: 
  host: localhost
  socket: "/tmp/mysql.sock"
 
test:
  <<:   *defaults
  database: billtrack_member_test
 
production:
  <<:   *defaults
  
  
  
# API data  
data_development:
  <<:   *defaults
  database: billtrack_data
  
data_test:
  <<:   *defaults
  database: billtrack_data_test
  
data_production:
  <<:   *defaults
  database: billtrack_data